### PR TITLE
Add license

### PR DESCRIPTION
**Pull request by shenvitor**

### CODE REVIEW

**Comment by redeboer** [comment]
Best to deactivate read the docs for now

**Comment by shenvitor** [comment]
> Best to deactivate read the docs for now

Okay, make sense for now.

**Comment by redeboer** [comment]
Good point, probably the only way is to deactivate previews for PRs.

**Review by redeboer — APPROVED** [review]
Yeah I would use either MIT or BSD, see https://choosealicense.com

**Review by redeboer — CHANGES_REQUESTED** [review]
Oh btw, can you add the license under pixi
https://pixi.sh/latest/reference/project_configuration/#license-optional

**Review by redeboer — APPROVED** [review]
🎉

**Pull request merged**
